export * from './About'
export * from './Contact'
export * from './Experience'
export * from './Feedbacks'
export * from './Hero'
export * from './Navbar'
export * from './Tech'
export * from './Works'